apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3-apps
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ./declarative/multiple-apps
    repoURL: 'https://github.com/edwindijkstrainmarsat/gitops-certification-examples.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
